# Generated by Django 2.1.3 on 2018-12-23 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s7uploads', '0002_upload_versionnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='upload',
            name='versionNotes',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='upload',
            name='versionNumber',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s7uploads.Upload'),
        ),
    ]
