# Generated by Django 2.1.3 on 2018-12-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s7uploads', '0003_auto_20181223_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='url',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='img',
            field=models.ImageField(default='nil.png', upload_to='s7uploads/images'),
            preserve_default=False,
        ),
    ]
