# Generated by Django 2.1.3 on 2018-12-29 02:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s7uploads', '0005_auto_20181223_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pubDate', models.DateTimeField(verbose_name='date published')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s7uploads.Upload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s7uploads.User')),
            ],
        ),
    ]
