# Generated by Django 2.1.3 on 2018-12-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s7uploads', '0007_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=2048, verbose_name='Review Text'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.TextField(max_length=2048, verbose_name='Upload Description'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='versionNotes',
            field=models.TextField(max_length=512, verbose_name='Version Notes'),
        ),
    ]
