# Generated by Django 2.1.3 on 2018-12-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s7uploads', '0008_auto_20181228_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.TextField(verbose_name='Upload Description'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='versionNotes',
            field=models.TextField(verbose_name='Version Notes'),
        ),
    ]
