# Generated by Django 2.2.12 on 2020-07-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s7uploads', '0013_auto_20200719_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='url',
        ),
    ]
