# Generated by Django 2.2.12 on 2021-01-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s7uploads', '0014_remove_upload_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='ranking',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
