# Generated by Django 2.2.12 on 2021-01-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s7uploads', '0015_auto_20210112_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ranking',
        ),
        migrations.AddField(
            model_name='uploadversion',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadversion',
            name='ranking',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
